Market/config/routes.rb
Market::Application.routes.draw do
  resources :people_books

  resources :people

  resources :books do
    member do
      get "message" 
    end
  end

end

Market/app/models/book.rb
class Book < ActiveRecord::Base
Twitter.configure do |config|
        config.consumer_key = 'hr5p3z7MlKvCN3Y9wghfQ'
        config.consumer_secret = 'MtCZ9Hks8b2we0piDd59UQkRuSyyRlVf51j4jSrVM'
        config.oauth_token = '261743114-6qjYzZ371L9lcay72ZfcEUqUXzWKBtxs5bH9NC61'
        config.oauth_token_secret = 'ij0TG01ZrzQ7kFBrCBOKgLxSiva3csQlcSwz2ELpHQ'
	end 

  def message (usuario ,cuenta)
        client = Twitter::Client.new
        client.update('Sr(a).' + '#' + usuario + ' ' + ' con cuenta ' + ' ' + cuenta + ' favor de entregar el libro ' + ' ' + self.title)
  end
	
  belongs_to :person
  attr_accessible :description, :title,:person_id, :days, :delivery_date
end

Market/app/models/people_book.rb
class PeopleBook < ActiveRecord::Base
end

Market/app/models/person.rb
class Person < ActiveRecord::Base
  has_many  :persons
  attr_accessible :account, :name
end

Market/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Market/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  
  def message
      @book = Book.find(params[:id])
  end
  
  
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

Market/app/controllers/people_books_controller.rb
class PeopleBooksController < ApplicationController
end

Market/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

Market/app/helpers/application_helper.rb
module ApplicationHelper
end

Market/app/helpers/books_helper.rb
module BooksHelper
end

Market/app/helpers/people_books_helper.rb
module PeopleBooksHelper
end

Market/app/helpers/people_helper.rb
module PeopleHelper
end

Market/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
	<%= f.label :person %><br />
	<%= f.collection_select :person_id, Person.all, :id, :name, :prompt => true %>
	</div>
  <div class="field">
    <%= f.label :delivery_date %><br />
    <%= f.text_field :delivery_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Market/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

Market/app/views/books/index.html.erb
<div data-role="page">
<p id="notice"><%= notice %></p>
  <div data-role="header">
    <h1>Listing books</h1>
  </div>

<div data-role="content">

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
	<th>Cliente</th>
    <th>Fecha</th>
    <th>Aviso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.description %></td>
	<td><%= book.person.name %></td>
    <td><%= book.delivery_date.strftime("%m/%d/%Y") %></td>
	<%if (Time.now) >= (book.delivery_date)%>
	<%= link_to 'Send notice', message_book_path(book) %>
	<%end%>
    </td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Book', new_book_path %>
</div>

Market/app/views/books/message.html.erb
<h1>Mensaje Enviado</h1>
<p><%=@book.message(@book.person.name ,@book.person.account)%></p>

Market/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

Market/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

Market/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Market/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account %><br />
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Market/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

Market/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.account %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

Market/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

Market/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Account:</b>
  <%= @person.account %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>